# Generated by Django 2.0.2 on 2018-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financilaMangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='公司代码'),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='industry',
            field=models.CharField(max_length=10, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='name',
            field=models.CharField(max_length=10, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='timeToMarket',
            field=models.CharField(max_length=10, verbose_name='上市时间'),
        ),
    ]
