# Generated by Django 2.0.2 on 2018-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financilaMangement', '0003_auto_20180304_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='timeToMarket',
            field=models.DateField(verbose_name='上市时间'),
        ),
    ]
