# Generated by Django 2.0.2 on 2018-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financilaMangement', '0004_auto_20180304_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='area',
            field=models.CharField(default='北京', max_length=10, verbose_name='所属地区'),
        ),
    ]
